---
- hosts: azure
  user: antonio
  vars:
    project_path: /home/antonio/proyecto
  tasks:
    - name: Crear directorio
      file:
        dest={{ project_path }}
        mode=0755
        recurse=yes
        state=directory
    - name: Clonar el repositorio
      git:
        repo: https://github.com/javiercabrera184/ProyectoCC.git
        dest: "{{ project_path }}"
    - name: Instalar npm
      become: true
      become_method: sudo
      apt:
        pkg=npm state=present
    - name: Importar clave publica
      become: true
      become_method: sudo
      command: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
    - name: Crear lista de archivos de mongo
      become: true
      become_method: sudo
      command: sudo echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubunt ubionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
    - name: Actualizar
      become: true
      become_method: sudo
      command: apt-get update
    - name: Instalar mongodb
      become: true
      become_method: sudo
      command: sudo apt-get install -y mongodb-org
    - name: Habilitar servicio
      become: true
      become_method: sudo
      command: service mongod start
    - name: Instala dependecias npm
      npm:
        path={{ project_path }}
    - name: Instala pm2
      become: true
      become_method: sudo
      npm:
        name: pm2
        global: yes
    - name: Elimina el proceso lanzado anteriormente
      command: pm2 delete PR
      ignore_errors: yes
    - name: Redirigir puertos
      become: true
      become_method: sudo
      command: iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000
    - name: Arrancar pm2
      command: pm2 start {{ project_path }}/app.js --name PR
    - name: Borrar directorio
      file:
        state: absent
        path: "{{ project_path }}"
