branches:
  only:
    - master
language: node_js
sudo: false
node_js:
  - node
install:
  - npm install mocha
deploy:
  provider: heroku
  strategy: git
  app: evening-anchorage-70354
  on:
    repo: javiercabrera184/ProyectoCC
